### ISSUE TITLE
release v0.1

### ISSUE THREAD

**Issue by keewis** [keewis/blackdoc#21]
Since most of the originally planned features are implemented:

- [x] CLI with checking and reformatting modes (#1)
- [x] format registering with enabling / disabling of specific formats (#2, #18), including:
  - [x] support for doctest
  - [x] support for rST (including most of the special syntax of the ipython sphinx directive) (#10)
- [x] file detection / filtering via include regex (#24)
- [x] documentation (though it could use more attention) (#19)
- [ ] add community guide lines (code of conduct, contributor guides, templates).
  Maybe we can copy most of these from `black`?

we can think of publishing a alpha release to PyPI.
